### ISSUE TITLE
Doesn't work with Vaadin 23.0.9. Add a note to the Vaadin Directory

### ISSUE THREAD

**Issue by simasch** [vaadin-component-factory/vcf-date-range-picker-flow#36]
When I use the EnhancedDateRangePicker with Vaadin 23.0.0 I get

`Caused by: java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.datepicker.GeneratedVaadinDatePicker.<init>(java.lang.Object, java.lang.Object, java.lang.Class, com.vaadin.flow.function.SerializableFunction, com.vaadin.flow.function.SerializableFunction)'`

**Comment by simasch** [comment]
Finally I've found out that there is a version 3.0.0

Please add a note that one has to use 3.0.0 with 23 to the Vaadin Directory

**Comment by paodb** [comment]
Both readme and Vaadin directory page now inlcude a Compatibility section.
